### PR TITLE
976 improve the documentation of the ide secir model

### LINKED ISSUE #976: Improve the documentation of the IDE-SECIR model
### Motivation / Current Behaviour

Currently, the documentation in the README of the IDE-SECIR model is not very detailed.

### Enhancement description

The documentation should be extended, especially by
- a section on initialization
- a diagram of the transitions (see also e.g. the ODE-SECIR model)
- a table showing the parameters used 

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

### PR DESCRIPTION
**Pull request by lenaploetzke**
# Changes and Information

Please **briefly list the changes** (main added features, changed items, or corrected bugs) made:

- Documentation of the IDE-SECIR model has been extended.
- Added a diagram of possible transitions.
-

If need be, add additional information and what the reviewer should look out for in particular:

- We could add the model equations to make clear how the parameters are used (e.g. in the ODE-SECIR model this is clear because of the picture). However, we would then have to specify the full equations of the compartments and the transitions.
-

## Merge Request - Guideline Checklist

Please check our [git workflow](https://github.com/SciCompMod/memilio/wiki/git-workflow). Use the **draft** feature if the Pull Request is not yet ready to review.

### Checks by code author

- [x] Every addressed issue is linked (use the "Closes #ISSUE" keyword below)
- [x] New code adheres to [coding guidelines](https://github.com/SciCompMod/memilio/wiki/Coding-guidelines)
- [x] No large data files have been added (files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [x] Tests are added for new functionality and a local test run was successful (with and without OpenMP)
- [x] Appropriate **documentation** for new functionality has been added (Doxygen in the code and Markdown files if necessary)
- [x] Proper attention to licenses, especially no new third-party software with conflicting license has been added
- [ ] (For ABM development) Checked [benchmark results](https://github.com/SciCompMod/memilio/wiki/Agent-Based-Model-Development) and ran and posted a local test above from before and after development to ensure performance is monitored.

### Checks by code reviewer(s)

- [ ] Corresponding issue(s) is/are linked and addressed
- [ ] Code is clean of development artifacts (no deactivated or commented code lines, no debugging printouts, etc.)
- [ ] Appropriate **unit tests** have been added, CI passes, code coverage and performance is acceptable (did not decrease)
- [ ] No large data files added in the whole history of commits(files should in sum not exceed 100 KB, avoid PDFs, Word docs, etc.)
- [ ] On merge, add 2-5 lines with the changes (main added features, changed items, or corrected bugs) to the merge-commit-message. This can be taken from the **briefly-list-the-changes** above (best case) or the separate commit messages (worst case).

Closes #976.

### CODE REVIEW

**Review by annawendler — CHANGES_REQUESTED** [review]
I liked the description and also the picture :) I made some suggestions. 

I'm actually unsure whether I would add the formulas for the compartments and transitions here. I'm not sure if the readme gets too long and overwhelming with the formulas. By looking at the table we still know which parameters play a role in our model.  On the other hand, without the formulas it is somehow incomplete as it is not clear where exactly the parameters go into the model as you mentioned. What is your opinion?

We should remember to only merge this PR after PR #952 so that the links work correctly.

**Comment by lenaploetzke** [comment]
I also think the formulas would be misplaced in the README. We should publish the paper instead and link it here :D For now, I think it's fine as it is.

I think we can also merge the PR before #952, the link should work if it's merged. Then we have already finished this PR, #952 will be finished soon.

**Review by annawendler — COMMENTED** [review]
I agree :D

I would still only merge after the other PR, I will look at it soon!

**Comment by annawendler** [comment]
This looks great and can be merged after PR #952 has been merged.

**Review by annawendler — APPROVED** [review]
Looks good!

**Pull request merged**
